### ISSUE TITLE
Client validations

### ISSUE THREAD

**Issue by santer545** [flowjs/ngx-flow#47]
Can I set the file size, file count and file extensions for Drag and drop? I didn`t see any option to validate adding files

**Comment by MartinNuc** [comment]
This is good point. I looked how is validation handled in flow.js and one have to return false from `fileAdded` event. This one is wrapped by ngx-flow means there is no way how to return false there 🙈

What you could do however is enable button only after all fails are valid:

```html
<button type="button" (click)="flow.upload()" [disabled]="failesAreValid$ | async">Start upload</button>
```

```typescript
this.failesAreValid$ = flow.transfers$.map(transfers =>  transfers.transfers.every(file => file.filename.endsWith('.txt'))
```

However we should have way how to use `fileAdded` event because that would be easier to use.

**Comment by santer545** [comment]
Thanks!
