### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by weijyewang** [flowjs/ngx-flow#6]
The demo example is not working

![image](https://user-images.githubusercontent.com/8890603/45733193-697c7f00-bc12-11e8-913f-c3b786dd745b.png)

**Comment by MartinNuc** [comment]
It is because we are transfering the package from `ngx-flow` to `@flowjs/ngx-flow` See https://github.com/flowjs/ngx-flow/issues/3 

Currently there is no way to install the package because the old `ngx-flow` was unpublished this morning and the new is not correctly published. I will try to ping @evilaliv3 about the progress.

**Comment by MartinNuc** [comment]
We managed to move package under @flowjs organization. I updated demo with new version. Now it should work.
